from ai_clinician.preprocessing.columns import *

C_OUTCOME = "outcome"
C_STATE = "state"
C_ACTION = "action"
C_REWARD = "reward"

C_SOFTENED_PHYSICIAN_PROBABILITY = "softened_physician_prob"
C_SOFTENED_MODEL_PROBABILITY = "softened_model_prob"
C_OPTIMAL_ACTION = "optimal_action"

# Add binary or categorical variables to AS_IS_COLUMNS
AS_IS_COLUMNS = [
    C_GENDER,
    C_MECHVENT,
    C_EXTUBATED,
    C_MAX_DOSE_VASO,
    C_RE_ADMISSION,
    C_APACHEII_RENAL_FAILURE,
    # Add more categorical variables here if needed
]

# Add continuous variables to NORM_COLUMNS
NORM_COLUMNS = [
    C_AGE, C_HEIGHT, C_WEIGHT, C_GCS, C_RASS, C_HR, C_SYSBP, C_MEANBP, C_DIABP, C_RR,
    C_TEMP_C, C_CVP, C_PAPSYS, C_PAPMEAN, C_PAPDIA, C_CI, C_FIO2_1, C_O2FLOW, C_PEEP,
    C_TIDALVOLUME, C_MINUTEVENTIL, C_PAWMEAN, C_PAWPEAK, C_PAWPLATEAU, C_POTASSIUM, C_SODIUM,
    C_CHLORIDE, C_GLUCOSE, C_MAGNESIUM, C_CALCIUM, C_IONISED_CA, C_TOTAL_PROTEIN, C_ALBUMIN,
    C_TROPONIN, C_HB, C_HT, C_RBC_COUNT, C_WBC_COUNT, C_PLATELETS_COUNT, C_PTT, C_PT,
    C_ACT, C_ARTERIAL_PH, C_PAO2, C_PACO2, C_ARTERIAL_BE, C_HCO3, C_ETCO2, C_ARTERIAL_LACTATE,
    C_SVO2, C_ANION_GAP, C_FIBRINOGEN, C_ABSOLUTE_NEUTROPHIL_COUNT, C_PHOSPHOROUS,
    C_SAO2, C_LDH, C_T3, C_OSMOLALITY_URINE,
    C_SOFA, C_SIRS, C_SHOCK_INDEX, C_PAO2_FIO2, C_CUMULATED_BALANCE,
    C_BLOOD_FLOW, C_HOURLY_PATIENT_FLUID_REMOVAL, C_DIALYSATE_RATE, C_ULTRAFILTRATE_OUTPUT, C_POTASSIUM_URINE, C_SODIUM_URINE, C_UREA_NITROGEN_URINE, C_HEPARIN_LMW, C_CREATININE_URINE
    #Missing Features:
    #C_OSMOLALITY_URINE, C_MYOGLOBIN, C_CREATININE_CLEARANCE, C_SCVO2, C_SVR
    #
    # Add more continuous variables here if needed
]

# Add skewed variables to LOG_NORM_COLUMNS
LOG_NORM_COLUMNS = [
    C_SPO2, C_BUN, C_CREATININE, C_SGOT, C_SGPT, C_TOTAL_BILI, C_INR,
    C_CRP, C_AMMONIA, C_TRIGLYCERIDE, C_CK_MB, C_BNP, C_THYROID_STIMULATING_HORMONE,
    C_HEMODIALYSIS_OUTPUT, C_CITRATE, C_PREFILTER_REPLACEMENT_RATE, C_POSTFILTER_REPLACEMENT_RATE, C_IRON,
    C_GAMMA_GLUTAMYLTRANSFERASE, C_INPUT_TOTAL, C_INPUT_STEP, C_OUTPUT_TOTAL, C_OUTPUT_STEP, 
    # Add more skewed variables here if needed
]

# Combine all feature columns
ALL_FEATURE_COLUMNS = AS_IS_COLUMNS + NORM_COLUMNS + LOG_NORM_COLUMNS



